services:
  app:
    build: .
    container_name: qa-assessment-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
